// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sso.proto

/*
Package sso is a generated protocol buffer package.

It is generated from these files:
	sso.proto

It has these top-level messages:
	SSHCertsRequest
	SSHCertsResponse
	ServerConfig
*/
package sso

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseCode int32

const (
	ResponseCode_OK               ResponseCode = 0
	ResponseCode_INVALID_ID_TOKEN ResponseCode = 1
	ResponseCode_NO_CERTS_ALLOWED ResponseCode = 2
)

var ResponseCode_name = map[int32]string{
	0: "OK",
	1: "INVALID_ID_TOKEN",
	2: "NO_CERTS_ALLOWED",
}
var ResponseCode_value = map[string]int32{
	"OK":               0,
	"INVALID_ID_TOKEN": 1,
	"NO_CERTS_ALLOWED": 2,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}
func (ResponseCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SSHCertsRequest struct {
	IdToken   string `protobuf:"bytes,1,opt,name=id_token,json=idToken" json:"id_token,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
}

func (m *SSHCertsRequest) Reset()                    { *m = SSHCertsRequest{} }
func (m *SSHCertsRequest) String() string            { return proto.CompactTextString(m) }
func (*SSHCertsRequest) ProtoMessage()               {}
func (*SSHCertsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SSHCertsRequest) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

func (m *SSHCertsRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type SSHCertsResponse struct {
	Status                 ResponseCode `protobuf:"varint,1,opt,name=status,enum=ResponseCode" json:"status,omitempty"`
	Certificate            string       `protobuf:"bytes,2,opt,name=certificate" json:"certificate,omitempty"`
	CertificateAuthorities []string     `protobuf:"bytes,3,rep,name=certificate_authorities,json=certificateAuthorities" json:"certificate_authorities,omitempty"`
	Config                 []string     `protobuf:"bytes,4,rep,name=config" json:"config,omitempty"`
}

func (m *SSHCertsResponse) Reset()                    { *m = SSHCertsResponse{} }
func (m *SSHCertsResponse) String() string            { return proto.CompactTextString(m) }
func (*SSHCertsResponse) ProtoMessage()               {}
func (*SSHCertsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SSHCertsResponse) GetStatus() ResponseCode {
	if m != nil {
		return m.Status
	}
	return ResponseCode_OK
}

func (m *SSHCertsResponse) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *SSHCertsResponse) GetCertificateAuthorities() []string {
	if m != nil {
		return m.CertificateAuthorities
	}
	return nil
}

func (m *SSHCertsResponse) GetConfig() []string {
	if m != nil {
		return m.Config
	}
	return nil
}

type ServerConfig struct {
	CaKeyPath                   string                              `protobuf:"bytes,1,opt,name=ca_key_path,json=caKeyPath" json:"ca_key_path,omitempty"`
	GenerateCertDurationSeconds int32                               `protobuf:"varint,2,opt,name=generate_cert_duration_seconds,json=generateCertDurationSeconds" json:"generate_cert_duration_seconds,omitempty"`
	AllowedUsers                map[string]*ServerConfig_UserConfig `protobuf:"bytes,4,rep,name=allowed_users,json=allowedUsers" json:"allowed_users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ListenPort                  int32                               `protobuf:"varint,5,opt,name=listen_port,json=listenPort" json:"listen_port,omitempty"`
	AllowedDomainForIdToken     string                              `protobuf:"bytes,6,opt,name=allowed_domain_for_id_token,json=allowedDomainForIdToken" json:"allowed_domain_for_id_token,omitempty"`
	AllowedClientIdForIdToken   string                              `protobuf:"bytes,7,opt,name=allowed_client_id_for_id_token,json=allowedClientIdForIdToken" json:"allowed_client_id_for_id_token,omitempty"`
	ServerCertPath              string                              `protobuf:"bytes,8,opt,name=server_cert_path,json=serverCertPath" json:"server_cert_path,omitempty"`
	ServerKeyPath               string                              `protobuf:"bytes,9,opt,name=server_key_path,json=serverKeyPath" json:"server_key_path,omitempty"`
	CaComment                   string                              `protobuf:"bytes,11,opt,name=ca_comment,json=caComment" json:"ca_comment,omitempty"`
	HttpListenPort              int32                               `protobuf:"varint,12,opt,name=http_listen_port,json=httpListenPort" json:"http_listen_port,omitempty"`
	AllowedHosts                []string                            `protobuf:"bytes,13,rep,name=allowed_hosts,json=allowedHosts" json:"allowed_hosts,omitempty"`
	CaddyFilePath               string                              `protobuf:"bytes,14,opt,name=caddy_file_path,json=caddyFilePath" json:"caddy_file_path,omitempty"`
	SshConnectForPublickeyPort  int32                               `protobuf:"varint,15,opt,name=ssh_connect_for_publickey_port,json=sshConnectForPublickeyPort" json:"ssh_connect_for_publickey_port,omitempty"`
	UserProfiles                map[string]*ServerConfig_Profile    `protobuf:"bytes,16,rep,name=user_profiles,json=userProfiles" json:"user_profiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ServerConfig) Reset()                    { *m = ServerConfig{} }
func (m *ServerConfig) String() string            { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()               {}
func (*ServerConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServerConfig) GetCaKeyPath() string {
	if m != nil {
		return m.CaKeyPath
	}
	return ""
}

func (m *ServerConfig) GetGenerateCertDurationSeconds() int32 {
	if m != nil {
		return m.GenerateCertDurationSeconds
	}
	return 0
}

func (m *ServerConfig) GetAllowedUsers() map[string]*ServerConfig_UserConfig {
	if m != nil {
		return m.AllowedUsers
	}
	return nil
}

func (m *ServerConfig) GetListenPort() int32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

func (m *ServerConfig) GetAllowedDomainForIdToken() string {
	if m != nil {
		return m.AllowedDomainForIdToken
	}
	return ""
}

func (m *ServerConfig) GetAllowedClientIdForIdToken() string {
	if m != nil {
		return m.AllowedClientIdForIdToken
	}
	return ""
}

func (m *ServerConfig) GetServerCertPath() string {
	if m != nil {
		return m.ServerCertPath
	}
	return ""
}

func (m *ServerConfig) GetServerKeyPath() string {
	if m != nil {
		return m.ServerKeyPath
	}
	return ""
}

func (m *ServerConfig) GetCaComment() string {
	if m != nil {
		return m.CaComment
	}
	return ""
}

func (m *ServerConfig) GetHttpListenPort() int32 {
	if m != nil {
		return m.HttpListenPort
	}
	return 0
}

func (m *ServerConfig) GetAllowedHosts() []string {
	if m != nil {
		return m.AllowedHosts
	}
	return nil
}

func (m *ServerConfig) GetCaddyFilePath() string {
	if m != nil {
		return m.CaddyFilePath
	}
	return ""
}

func (m *ServerConfig) GetSshConnectForPublickeyPort() int32 {
	if m != nil {
		return m.SshConnectForPublickeyPort
	}
	return 0
}

func (m *ServerConfig) GetUserProfiles() map[string]*ServerConfig_Profile {
	if m != nil {
		return m.UserProfiles
	}
	return nil
}

type ServerConfig_UserConfig struct {
	Profiles []string `protobuf:"bytes,4,rep,name=profiles" json:"profiles,omitempty"`
}

func (m *ServerConfig_UserConfig) Reset()                    { *m = ServerConfig_UserConfig{} }
func (m *ServerConfig_UserConfig) String() string            { return proto.CompactTextString(m) }
func (*ServerConfig_UserConfig) ProtoMessage()               {}
func (*ServerConfig_UserConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *ServerConfig_UserConfig) GetProfiles() []string {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type ServerConfig_Profile struct {
	Principals      []string          `protobuf:"bytes,1,rep,name=principals" json:"principals,omitempty"`
	CertPermissions map[string]string `protobuf:"bytes,2,rep,name=cert_permissions,json=certPermissions" json:"cert_permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SshConfigLines  []string          `protobuf:"bytes,3,rep,name=ssh_config_lines,json=sshConfigLines" json:"ssh_config_lines,omitempty"`
	KnownHosts      []string          `protobuf:"bytes,4,rep,name=known_hosts,json=knownHosts" json:"known_hosts,omitempty"`
}

func (m *ServerConfig_Profile) Reset()                    { *m = ServerConfig_Profile{} }
func (m *ServerConfig_Profile) String() string            { return proto.CompactTextString(m) }
func (*ServerConfig_Profile) ProtoMessage()               {}
func (*ServerConfig_Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *ServerConfig_Profile) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *ServerConfig_Profile) GetCertPermissions() map[string]string {
	if m != nil {
		return m.CertPermissions
	}
	return nil
}

func (m *ServerConfig_Profile) GetSshConfigLines() []string {
	if m != nil {
		return m.SshConfigLines
	}
	return nil
}

func (m *ServerConfig_Profile) GetKnownHosts() []string {
	if m != nil {
		return m.KnownHosts
	}
	return nil
}

func init() {
	proto.RegisterType((*SSHCertsRequest)(nil), "SSHCertsRequest")
	proto.RegisterType((*SSHCertsResponse)(nil), "SSHCertsResponse")
	proto.RegisterType((*ServerConfig)(nil), "ServerConfig")
	proto.RegisterType((*ServerConfig_UserConfig)(nil), "ServerConfig.UserConfig")
	proto.RegisterType((*ServerConfig_Profile)(nil), "ServerConfig.Profile")
	proto.RegisterEnum("ResponseCode", ResponseCode_name, ResponseCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GeeCertServer service

type GeeCertServerClient interface {
	GetSSHCerts(ctx context.Context, in *SSHCertsRequest, opts ...grpc.CallOption) (*SSHCertsResponse, error)
}

type geeCertServerClient struct {
	cc *grpc.ClientConn
}

func NewGeeCertServerClient(cc *grpc.ClientConn) GeeCertServerClient {
	return &geeCertServerClient{cc}
}

func (c *geeCertServerClient) GetSSHCerts(ctx context.Context, in *SSHCertsRequest, opts ...grpc.CallOption) (*SSHCertsResponse, error) {
	out := new(SSHCertsResponse)
	err := grpc.Invoke(ctx, "/GeeCertServer/GetSSHCerts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GeeCertServer service

type GeeCertServerServer interface {
	GetSSHCerts(context.Context, *SSHCertsRequest) (*SSHCertsResponse, error)
}

func RegisterGeeCertServerServer(s *grpc.Server, srv GeeCertServerServer) {
	s.RegisterService(&_GeeCertServer_serviceDesc, srv)
}

func _GeeCertServer_GetSSHCerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHCertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeeCertServerServer).GetSSHCerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeeCertServer/GetSSHCerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeeCertServerServer).GetSSHCerts(ctx, req.(*SSHCertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeeCertServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GeeCertServer",
	HandlerType: (*GeeCertServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSSHCerts",
			Handler:    _GeeCertServer_GetSSHCerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso.proto",
}

func init() { proto.RegisterFile("sso.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 804 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0xdd, 0x8e, 0x1a, 0x37,
	0x14, 0x0e, 0x6c, 0x97, 0x5d, 0x0e, 0x7f, 0xb3, 0xd6, 0x36, 0x99, 0x10, 0x85, 0xac, 0xa8, 0x5a,
	0xa1, 0x54, 0x9a, 0x0b, 0x5a, 0xa9, 0x55, 0xd5, 0x1b, 0x76, 0x60, 0x13, 0x04, 0x5a, 0x10, 0x6c,
	0x52, 0xf5, 0xca, 0x9a, 0xcc, 0x18, 0xb0, 0x76, 0xb0, 0xa7, 0xb6, 0x27, 0x11, 0x4f, 0xd1, 0x17,
	0xe9, 0x23, 0xf4, 0xe1, 0x22, 0xdb, 0x33, 0x30, 0x64, 0xb9, 0x1b, 0x7f, 0xfe, 0xfc, 0x9d, 0xe3,
	0xef, 0x1c, 0x9f, 0x81, 0xaa, 0x94, 0xdc, 0x4b, 0x04, 0x57, 0xbc, 0x3b, 0x81, 0xd6, 0x72, 0xf9,
	0xde, 0x27, 0x42, 0xc9, 0x05, 0xf9, 0x27, 0x25, 0x52, 0xa1, 0x97, 0x70, 0x49, 0x23, 0xac, 0xf8,
	0x23, 0x61, 0x6e, 0xe9, 0xa6, 0xd4, 0xab, 0x2e, 0x2e, 0x68, 0xf4, 0xa0, 0x97, 0xe8, 0x35, 0x40,
	0x92, 0x7e, 0x8a, 0x69, 0x88, 0x1f, 0xc9, 0xce, 0x2d, 0x9b, 0xcd, 0xaa, 0x45, 0x26, 0x64, 0xd7,
	0xfd, 0xaf, 0x04, 0xce, 0x41, 0x4d, 0x26, 0x9c, 0x49, 0x82, 0x7e, 0x84, 0x8a, 0x54, 0x81, 0x4a,
	0xa5, 0x11, 0x6b, 0xf6, 0x1b, 0x5e, 0xbe, 0xe5, 0xf3, 0x88, 0x2c, 0xb2, 0x4d, 0x74, 0x03, 0xb5,
	0x90, 0x08, 0x45, 0x57, 0x34, 0x0c, 0x14, 0xc9, 0xb4, 0x8b, 0x10, 0xfa, 0x0d, 0x5e, 0x14, 0x96,
	0x38, 0x48, 0xd5, 0x86, 0x0b, 0xaa, 0x28, 0x91, 0xee, 0xd9, 0xcd, 0x59, 0xaf, 0xba, 0x78, 0x5e,
	0xd8, 0x1e, 0x1c, 0x76, 0xd1, 0x73, 0xa8, 0x84, 0x9c, 0xad, 0xe8, 0xda, 0xfd, 0xce, 0xf0, 0xb2,
	0x55, 0xf7, 0xff, 0x2a, 0xd4, 0x97, 0x44, 0x7c, 0x26, 0xc2, 0x37, 0x00, 0xea, 0x40, 0x2d, 0x0c,
	0xf4, 0xd5, 0x70, 0x12, 0xa8, 0x4d, 0x76, 0xf9, 0x6a, 0x18, 0x4c, 0xc8, 0x6e, 0x1e, 0xa8, 0x0d,
	0xf2, 0xa1, 0xb3, 0x26, 0x8c, 0x08, 0x1d, 0x5e, 0xc7, 0xc2, 0x51, 0x2a, 0x02, 0x45, 0x39, 0xc3,
	0x92, 0x84, 0x9c, 0x45, 0xd2, 0xa4, 0x7d, 0xbe, 0x78, 0x95, 0xb3, 0xb4, 0x13, 0xc3, 0x8c, 0xb3,
	0xb4, 0x14, 0x34, 0x84, 0x46, 0x10, 0xc7, 0xfc, 0x0b, 0x89, 0x70, 0x2a, 0x89, 0x90, 0x26, 0xa9,
	0x5a, 0xff, 0x8d, 0x57, 0x4c, 0xc5, 0x1b, 0x58, 0xca, 0x07, 0xcd, 0x18, 0x31, 0x25, 0x76, 0x8b,
	0x7a, 0x50, 0x80, 0xd0, 0x1b, 0xa8, 0xc5, 0x54, 0x2a, 0xc2, 0x70, 0xc2, 0x85, 0x72, 0xcf, 0x4d,
	0x5c, 0xb0, 0xd0, 0x9c, 0x0b, 0x85, 0xfe, 0x84, 0x57, 0x79, 0x98, 0x88, 0x6f, 0x03, 0xca, 0xf0,
	0x8a, 0x0b, 0xbc, 0x2f, 0x6c, 0xc5, 0xdc, 0xed, 0x45, 0x46, 0x19, 0x1a, 0xc6, 0x1d, 0x17, 0xe3,
	0xac, 0xd0, 0x03, 0xe8, 0xe4, 0xa7, 0xc3, 0x98, 0x12, 0xa6, 0xf4, 0xc9, 0x23, 0x81, 0x0b, 0x23,
	0xf0, 0x32, 0x63, 0xf9, 0x86, 0x34, 0x8e, 0x0a, 0x12, 0x3d, 0x70, 0xa4, 0xb9, 0x91, 0xb5, 0xca,
	0x38, 0x7a, 0x69, 0x0e, 0x35, 0x2d, 0xae, 0xcd, 0x31, 0xb6, 0xfe, 0x04, 0xad, 0x8c, 0xb9, 0xb7,
	0xbe, 0x6a, 0x88, 0x0d, 0x0b, 0xe7, 0xf6, 0xbf, 0x06, 0x08, 0x03, 0x1c, 0xf2, 0xed, 0x96, 0x30,
	0xe5, 0xd6, 0xf2, 0xea, 0xf8, 0x16, 0xd0, 0x01, 0x37, 0x4a, 0x25, 0xb8, 0xe8, 0x4b, 0xdd, 0xf8,
	0xd2, 0xd4, 0xf8, 0xf4, 0xe0, 0xcd, 0x0f, 0x87, 0x12, 0x6c, 0xb8, 0x54, 0xd2, 0x6d, 0x98, 0xbe,
	0xc8, 0x1d, 0x7e, 0xaf, 0x31, 0x9d, 0x55, 0x18, 0x44, 0xd1, 0x0e, 0xaf, 0x68, 0x4c, 0x6c, 0x56,
	0x4d, 0x9b, 0x95, 0x81, 0xef, 0x68, 0x4c, 0x4c, 0x56, 0xb7, 0xd0, 0x91, 0x72, 0x83, 0x43, 0xce,
	0x18, 0x09, 0x95, 0x31, 0xc9, 0xbe, 0x08, 0x73, 0x19, 0x9d, 0x44, 0xcb, 0x24, 0xd1, 0x96, 0x72,
	0xe3, 0x5b, 0xd2, 0x1d, 0x17, 0xf3, 0x9c, 0x62, 0x12, 0x1a, 0x42, 0x43, 0xf7, 0x02, 0x4e, 0x04,
	0xd7, 0xd1, 0xa4, 0xeb, 0x9c, 0xea, 0x09, 0x5d, 0xf9, 0x79, 0xc6, 0xc8, 0x7a, 0x22, 0x2d, 0x40,
	0xed, 0x1e, 0x80, 0xa6, 0x64, 0xcd, 0xdc, 0x86, 0xcb, 0xbd, 0x9c, 0xed, 0xfb, 0xfd, 0xba, 0xfd,
	0x6f, 0x19, 0x2e, 0xb2, 0x63, 0xa8, 0x03, 0x90, 0x08, 0xca, 0x42, 0x9a, 0x04, 0xb1, 0x7e, 0xa3,
	0x9a, 0x59, 0x40, 0xd0, 0x07, 0x70, 0x6c, 0x01, 0x89, 0xd8, 0x52, 0x29, 0x29, 0x67, 0xba, 0xcd,
	0x75, 0x7a, 0x6f, 0x8f, 0xd3, 0xcb, 0x04, 0x3d, 0x53, 0xd7, 0x03, 0xd9, 0x66, 0xda, 0x0a, 0x8f,
	0x51, 0xd3, 0x1e, 0xd6, 0xb6, 0x15, 0x5d, 0xe3, 0x98, 0xb2, 0xfd, 0x33, 0x6e, 0x5a, 0xa3, 0x56,
	0x74, 0x3d, 0xd5, 0xa8, 0x6e, 0xf5, 0x47, 0xc6, 0xbf, 0xb0, 0xac, 0x56, 0xf6, 0x2e, 0x60, 0x20,
	0x53, 0xa9, 0xf6, 0x2d, 0x5c, 0x9f, 0x8a, 0x89, 0x1c, 0x38, 0xd3, 0x63, 0xca, 0x3e, 0x63, 0xfd,
	0x89, 0xae, 0xe1, 0xfc, 0x73, 0x10, 0xa7, 0xf9, 0x78, 0xb1, 0x8b, 0x3f, 0xca, 0xbf, 0x97, 0xda,
	0x7f, 0xc3, 0xd5, 0x93, 0x27, 0x77, 0x42, 0xc0, 0x2b, 0x0a, 0xd4, 0xfa, 0xee, 0xd3, 0x02, 0xd9,
	0xcf, 0xa2, 0xf4, 0x47, 0xb8, 0x7a, 0x52, 0xb9, 0x13, 0xd2, 0x3f, 0x1f, 0x4b, 0x7f, 0x7f, 0xd2,
	0xdc, 0x82, 0xee, 0xdb, 0x5b, 0xa8, 0x17, 0x27, 0x29, 0xaa, 0x40, 0x79, 0x36, 0x71, 0x9e, 0xa1,
	0x6b, 0x70, 0xc6, 0xf7, 0x1f, 0x07, 0xd3, 0xf1, 0x10, 0x8f, 0x87, 0xf8, 0x61, 0x36, 0x19, 0xdd,
	0x3b, 0x25, 0x8d, 0xde, 0xcf, 0xb0, 0x3f, 0x5a, 0x3c, 0x2c, 0xf1, 0x60, 0x3a, 0x9d, 0xfd, 0x35,
	0x1a, 0x3a, 0xe5, 0xfe, 0x08, 0x1a, 0xef, 0x88, 0x19, 0x53, 0x36, 0x1a, 0xfa, 0x15, 0x6a, 0xef,
	0x88, 0xca, 0x87, 0x38, 0x72, 0xbc, 0x6f, 0xfe, 0x0e, 0xed, 0x2b, 0xef, 0xdb, 0x09, 0xdf, 0x7d,
	0xf6, 0xa9, 0x62, 0x7e, 0x26, 0xbf, 0x7c, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x90, 0x75, 0x89,
	0x59, 0x06, 0x00, 0x00,
}
